### ISSUE TITLE
Start, Stop, Restart and Get Status for Service Torrent

### ISSUE THREAD

**Issue by WPBC** [metahashorg/Node-Torrent#4]
Here is the shell script for Start, Stop, Restart and getting Status of Service Torrent
[Sefice-Torrent-Shell-Script.zip](https://github.com/metahashorg/Node-Torrent/files/4217243/Sefice-Torrent-Shell-Script.zip)

**Comment by magisterRab** [comment]
Thanks!

**Comment by WPBC** [comment]
Your very welcome
